### ISSUE TITLE
Running WSF External Workloads on a Kubernetes Pod without using terraform docker image

### ISSUE THREAD

**Issue by saiprasanna7** [intel/workload-services-framework#20]
### Summary
We are exploring the possibility of running WSF external workloads on a K8s pod. We are considering the 23.1 branch of WSF. Our primary objective is to determine if it's feasible to execute these workloads directly on the pod (just like a local execution), without the need to pull Docker images for running the workload.

#### Platform
Kubernetes EKS 1.23 

#### What is expected? 
Ability to run workloads on a pod without using the docker image of Terraform as it does on Jenkins jobs. Can we achieve this?

**Comment by Michael-M-Zhang** [comment]
@saiprasanna7  The WSF support pure docker , kubernetes and Terrafom backend. you can see if the kubernetes backend can meet your request.

**Comment by saiprasanna7** [comment]
It is working with the Kubernetes backend. Thank you!
